version: '3.8'

services:
  app:
    image: mbirk2/archive
    container_name: archive
    ports:
      - '8080:80'
    deploy:
      update_config:
        parallelism: 1
        order: start-first
    restart: always
    pull_policy: always
  archive-db:
    image: 'postgres:16.3'
    container_name: archive-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=archive-db
      - POSTGRES_PASSWORD=V40jN2gavmfj1q9Ln5Aq
      - PGUSER=archive-db
      - POSTGRES_DB=archive
